//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainmenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cagtegory
    {
        public string categoryID { get; set; }
        public string categoryName { get; set; }
        public string categoryDescription { get; set; }
        public string inventory { get; set; }
        public string reason { get; set; }
    }
}
